# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-02 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.CharField(default='Senior', max_length=50),
            preserve_default=False,
        ),
    ]
