# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20160506_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
