# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('linkedin_url', models.CharField(max_length=50)),
            ],
        ),
    ]
